---
- name: Central Playbook
  hosts: all
  become: yes
  
  vars:
    fedora_packages:
      - lshw
      - nvme-cli
      - smartmontools
      - flatpak
      - vulkan-tools
      - python3-pip
      - rustup
      - golang
      - zsh
      - git
      - ethtool
      - hdparm
    debian_packages:
      - lshw
      - nvme-cli
      - smartmontools
      - flatpak
      - vulkan-tools
      - python3-pip
      - rustup
      - golang
      - zsh
      - git
      - ethtool
      - hdparm
    endeavoros_packages:
      - lshw
      - nvme-cli
      - smartmontools
      - flatpak
      - vulkan-tools
      - python-pip
      - rustup
      - go
      - zsh
      - git
      - ethtool
      - hdparm  
  roles:
    - common
    - gpu
    - flatpak
    - dev_tools
    - zsh
    - wakeonlan
    - wayland
    #- hyprland
    - emulators
    - torrenting
    - k8s_tools
