---
- name: Install Wii U Emulator (Cemu)
  shell: |
    if [[ "{{ os_id.stdout }}" == *"debian"* ]]; then
      sudo apt install -y wine
      wget https://cemu.info/releases/cemu_1.25.6.zip -O /tmp/cemu.zip
      unzip /tmp/cemu.zip -d /opt/cemu
    elif [[ "{{ os_id.stdout }}" == *"fedora"* ]]; then
      sudo dnf install -y wine
      wget https://cemu.info/releases/cemu_1.25.6.zip -O /tmp/cemu.zip
      unzip /tmp/cemu.zip -d /opt/cemu
    elif [[ "{{ os_id.stdout }}" == *"endeavouros"* ]]; then
      sudo pacman -Syu wine
      wget https://cemu.info/releases/cemu_1.25.6.zip -O /tmp/cemu.zip
      unzip /tmp/cemu.zip -d /opt/cemu
    fi
  args:
    creates: /opt/cemu

- name: Download and set up Breath of the Wild
  shell: |
    mkdir -p /opt/cemu/Games
    wget <URL_TO_BOTW> -O /opt/cemu/Games/BreathOfTheWild.zip
    unzip /opt/cemu/Games/BreathOfTheWild.zip -d /opt/cemu/Games/BreathOfTheWild
  args:
    creates: /opt/cemu/Games/BreathOfTheWild

- name: Install Yuzu Emulator
  shell: |
    if [[ "{{ os_id.stdout }}" == *"debian"* ]]; then
      sudo add-apt-repository ppa:jonathonf/yuzu -y
      sudo apt update
      sudo apt install -y yuzu
    elif [[ "{{ os_id.stdout }}" == *"fedora"* ]]; then
      sudo dnf config-manager --add-repo=https://copr.fedorainfracloud.org/coprs/geoffw/yuzu/repo/fedora-32/geoffw-yuzu-fedora-32.repo
      sudo dnf install -y yuzu
    elif [[ "{{ os_id.stdout }}" == *"endeavouros"* ]]; then
      yay -S yuzu-mainline-bin
    fi
  args:
    creates: /usr/bin/yuzu
