---
- name: Determine the OS
  shell: cat /etc/os-release | grep "^ID="
  register: os_id
  changed_when: false

# TODO: fix
# - name: Install Wii U Emulator (Cemu)
#   shell: |
#     if [[ "{{ os_id.stdout }}" == *"debian"* ]]; then
#       apt install -y wine
#       wget https://cemu.info/releases/cemu_1.25.6.zip -O /tmp/cemu.zip
#       unzip /tmp/cemu.zip -d /opt/cemu
#     elif [[ "{{ os_id.stdout }}" == *"fedora"* ]]; then
#       dnf install -y wine
#       wget https://cemu.info/releases/cemu_1.25.6.zip -O /tmp/cemu.zip
#       unzip /tmp/cemu.zip -d /opt/cemu
#     elif [[ "{{ os_id.stdout }}" == *"endeavouros"* ]]; then
#       pacman -Syu wine
#       wget https://cemu.info/releases/cemu_1.25.6.zip -O /tmp/cemu.zip
#       unzip /tmp/cemu.zip -d /opt/cemu
#     fi
#   args:
#     creates: /opt/cemu
#   become: true

# - name: Download and set up Breath of the Wild
#   shell: |
#     mkdir -p /opt/cemu/Games
#     wget <URL_TO_BOTW> -O /opt/cemu/Games/BreathOfTheWild.zip
#     unzip /opt/cemu/Games/BreathOfTheWild.zip -d /opt/cemu/Games/BreathOfTheWild
#   args:
#     creates: /opt/cemu/Games/BreathOfTheWild

# - name: Install Yuzu Emulator
#   shell: |
#     if [[ "{{ os_id.stdout }}" == *"debian"* ]]; then
#       add-apt-repository ppa:jonathonf/yuzu -y
#       apt update
#       apt install -y yuzu
#     elif [[ "{{ os_id.stdout }}" == *"fedora"* ]]; then
#       dnf config-manager --add-repo=https://copr.fedorainfracloud.org/coprs/geoffw/yuzu/repo/fedora-32/geoffw-yuzu-fedora-32.repo
#       dnf install -y yuzu
#     elif [[ "{{ os_id.stdout }}" == *"endeavouros"* ]]; then
#       yay -S yuzu-mainline-bin
#     fi
#   args:
#     creates: /usr/bin/yuzu
#   become: true

- name: Install applications as Flatpaks
  flatpak:
    name: "{{ item }}"
    state: present
    remote: flathub
  loop:
    - net.kuribo64.melonDS
    - org.libretro.RetroArch
    - org.duckstation.DuckStation
    - io.github.shiiion.primehack
    - app.xemu.xemu
