---
- name: Install torrenting tools
  package:
    name: "{{ item }}"
    state: present
  loop:
    - qbittorrent
    - transmission-cli
    - transmission-daemon
  when: ansible_os_family == 'RedHat'
  become: true

- name: Install torrenting tools
  package:
    name: "{{ item }}"
    state: present
  loop:
    - qbittorrent
    - transmission-cli
    - transmission-daemon
  when: ansible_os_family == 'Debian'
  become: true
  
- name: Install torrenting tools
  package:
    name: "{{ item }}"
    state: present
  loop:
    - libtransmission
    - transmission-cli
    - transmission-gtk
  when: ansible_os_family == 'Archlinux'
  become: true
  
- name: Download Tor Browser tarball
  become: true
  get_url:
    url: https://www.torproject.org/dist/torbrowser/13.5.7/tor-browser-linux-x86_64-13.5.7.tar.xz
    dest: /tmp/tor-browser-linux-x86_64.tar.xz

- name: Extract Tor Browser
  become: true
  unarchive:
    src: /tmp/tor-browser-linux-x86_64.tar.xz
    dest: /opt/
    remote_src: yes

# - name: Create symbolic link for Tor Browser
#   become: true
#   file:
#     src: /opt/tor-browser/start-tor-browser.desktop
#     dest: /usr/local/bin/tor-browser
#     state: link

- name: Create desktop entry for Tor Browser
  become: true
  copy:
    dest: /usr/share/applications/tor-browser.desktop
    content: |
      [Desktop Entry]
      Name=Tor Browser
      Exec=/opt/tor-browser/start-tor-browser.desktop
      Icon=/opt/tor-browser/Browser/browser/chrome/icons/default/default128.png
      Type=Application
      Categories=Network;WebBrowser;
      Comment=Browse the web anonymously with Tor Browser
      Terminal=false
