---
- name: Install Visual Studio Code
  shell: |
    if [[ "{{ os_id.stdout }}" == *"debian"* ]]; then
      wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg
      sudo install -o root -g root -m 644 packages.microsoft.gpg /usr/share/keyrings/
      sudo sh -c 'echo "deb [arch=amd64 signed-by=/usr/share/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" > /etc/apt/sources.list.d/vscode.list'
      sudo apt-get install apt-transport-https
      sudo apt-get update
      sudo apt-get install code
    elif [[ "{{ os_id.stdout }}" == *"fedora"* ]]; then
      sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
      sudo sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo'
      sudo dnf install code
    elif [[ "{{ os_id.stdout }}" == *"endeavouros"* ]]; then
      yay -S visual-studio-code-bin
    fi
  args:
    creates: /usr/bin/code

- name: Install VSCodium
  shell: |
    if [[ "{{ os_id.stdout }}" == *"debian"* ]]; then
      wget -qO - https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg | sudo apt-key add -
      echo 'deb [arch=amd64] https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/debs/ vscodium main' | sudo tee --append /etc/apt/sources.list.d/vscodium.list
      sudo apt update
      sudo apt install codium
    elif [[ "{{ os_id.stdout }}" == *"fedora"* ]]; then
      sudo rpmkeys --import https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg
      echo -e "[gitlab.com_paulcarroty_vscodium]\nname=VSCodium\nbaseurl=https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/rpms/\nenabled=1\ngpgcheck=1\ngpgkey=https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg" | sudo tee /etc/yum.repos.d/vscodium.repo
      sudo dnf install codium
    elif [[ "{{ os_id.stdout }}" == *"endeavouros"* ]]; then
      yay -S vscodium-bin
    fi
  args:
    creates: /usr/bin/codium

- name: Install asdf and plugins
  shell: |
    git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.10.0
    echo '. $HOME/.asdf/asdf.sh' >> ~/.bashrc
    source ~/.bashrc
    asdf plugin-add nodejs https://github.com/asdf-vm/asdf-nodejs.git
    asdf install nodejs latest
    asdf global nodejs latest
  args:
    creates: ~/.asdf

- name: Install Golang
  package:
    name: golang
    state: present

- name: Install Miniconda
  shell: |
    wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O /tmp/miniconda.sh
    bash /tmp/miniconda.sh -b -p $HOME/miniconda
    $HOME/miniconda/bin/conda init zsh
  args:
    creates: $HOME/miniconda

- name: Install Poetry
  pip:
    name: poetry
    

- name: Install Molecule
  pip:
    name: molecule

- name: Install rustup
  shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  args:
    creates: /usr/local/bin/rustup
