---
- name: Enable Wayland
  package:
    name: "{{ item }}"
    state: present
  loop:
     - wayland
     - gnome-session-wayland
     - xorg-xwayland
     - qt6-wayland
     # Not sure if needed:
     #- xwaylandvideobridge
 
- name: Copy Elrctron config
  become: false
  copy:
    src: electron-flags.conf
    dest: ~/.config/electron-flags.conf
    mode: '0644'
