---
- name: Install and configure Flatpak
  package:
    name: flatpak
    state: present
  when: os_id.stdout.find('fedora') != -1 or os_id.stdout.find('debian') != -1 or os_id.stdout.find('endeavouros') != -1

- name: Add Flathub repository
  command: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

- name: Remove native versions of applications
  package:
    name: "{{ item }}"
    state: absent
  loop:
    - thunderbird
    - onlyoffice
    - calibre
    - standardnotes
    - ardour
    - firefox

- name: Install applications as Flatpaks
  flatpak:
    name: "{{ item }}"
    state: present
    remote: flathub
  loop:
    - org.mozilla.Thunderbird
    - org.onlyoffice.desktopeditors
    - com.calibre_ebook.calibre
    - org.standardnotes.standardnotes
    - org.ardour.Ardour
    - org.mozilla.firefox
    - com.vscodium.codium
    - org.wezfurlong.wezterm

# - name: Install Calibre DeDRM_tools plugin
#   shell: |
#     mkdir -p ~/.config/calibre/plugins
#     wget https://github.com/noDRM/DeDRM_tools/releases/download/v7.2.1/DeDRM_plugin.zip -O ~/.config/calibre/plugins/DeDRM_plugin.zip
#     calibre-customize -b ~/.config/calibre/plugins/DeDRM_plugin.zip
#   args:
#     creates: ~/.config/calibre/plugins/DeDRM_plugin.zip

- name: Create symlink for codium CLI
  file:
    src: /var/lib/flatpak/exports/bin/com.vscodium.codium
    dest: /usr/local/bin/codium
    state: link
    force: yes

- name: Ensure codium CLI is executable
  file:
    path: /usr/local/bin/codium
    mode: '0755'
    state: file

- name: Verify codium command works
  command: codium --version
  register: result
  changed_when: False
  failed_when: result.rc != 0
  ignore_errors: yes

- name: Debug codium command output
  debug:
    var: result.stdout
  when: result.rc == 0

