---
- name: Install Docker
  block:
    - name: Install Docker dependencies
      package:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
      when: ansible_os_family == 'Debian'
      become: true

    - name: Add Docker GPG key
      command: curl -fsSL https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg | sudo apt-key add -
      when: ansible_os_family == 'Debian'
      become: true

    - name: Add Docker repository
      command: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} $(lsb_release -cs) stable"
      when: ansible_os_family == 'Debian'
      become: true

    - name: Update package index
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'
      become: true

    - name: Install Docker CE
      package:
        name: 
        - docker-ce
        - docker-ce-cli 
        - containerd.io 
        - docker-buildx-plugin 
        - docker-compose-plugin
        state: present
      when: ansible_os_family == 'Debian'
      become: true

    - name: enable dnf repo
      shell: |
        dnf -y install dnf-plugins-core
        dnf-3 config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
      become: true

    - name: Install Docker on Fedora
      package:
        name: 
        - docker-ce
        - docker-ce-cli 
        - containerd.io 
        - docker-buildx-plugin 
        - docker-compose-plugin
        state: present
      when: ansible_os_family == 'RedHat'
      become: true
      
    - name: Install Docker on Arch-based systems
      package:
        name: 
        - docker
        - docker-compose
        state: present
      when: ansible_os_family == 'Archlinux'
      become: true

    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: yes
      become: true

    - name: Add user to the docker group
      ansible.builtin.user:
        name: "{{ lookup('env', 'USER') }}"
        group: docker
      become: true

- name: Install kubectl
  block:
    - name: Install kubectl on Debian-based systems
      package:
        name: kubectl
        state: present
      when: ansible_os_family == 'Debian'
      become: true

    - name: Install kubectl on Fedora-based systems
      package:
        name: kubernetes-client
        state: present
      when: ansible_os_family == 'RedHat'
      become: true

    - name: Install kubectl on Arch-based systems
      package:
        name: kubectl
        state: present
      when: ansible_os_family == 'Archlinux'
      become: true

# TODO: fix
#- name: Install k9s 
#  block:
#    - name: Install k9s
#      package:
#        name: k9s
#        state: present
#    become: true

- name: Download k3sup
  shell: curl -sLS https://get.k3sup.dev | sh
    
- name: Install k3sup
  become: true
  copy:
    remote_src: true
    src: ./k3sup
    dest: /usr/local/bin/k3sup

- name: Install Helm
  block:
    - name: Install Helm on Debian-based systems
      shell: |
        curl https://baltocdn.com/helm/signing.asc | sudo apt-key add -
        sudo apt-get install apt-transport-https --yes
        echo "deb https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
        sudo apt-get update
        sudo apt-get install helm
      when: ansible_os_family == 'Debian'

    - name: Install Helm on Fedora-based systems
      shell: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      when: ansible_os_family == 'RedHat'

    - name: Install Helm on Arch-based systems
      pacman:
        name: helm
        state: present
      when: ansible_os_family == 'Archlinux'
