---
- name: Install Docker
  block:
    - name: Install Docker dependencies
      package:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
      when: ansible_os_family == 'Debian'

    - name: Add Docker GPG key
      command: curl -fsSL https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg | sudo apt-key add -
      when: ansible_os_family == 'Debian'

    - name: Add Docker repository
      command: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} $(lsb_release -cs) stable"
      when: ansible_os_family == 'Debian'

    - name: Update package index
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: Install Docker CE
      package:
        name: 
        - docker-ce
        - docker-ce-cli 
        - containerd.io 
        - docker-buildx-plugin 
        - docker-compose-plugin
        state: present
      when: ansible_os_family == 'Debian'

    - name: Install Docker on Fedora
      package:
        name: 
        - docker-ce
        - docker-ce-cli 
        - containerd.io 
        - docker-buildx-plugin 
        - docker-compose-plugin
        state: present
      when: ansible_os_family == 'RedHat'
      
    - name: Install kubectl on Arch-based systems
      package:
        name: 
        - docker
        - docker-compose
        state: present
      when: ansible_os_family == 'Archlinux'

    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

- name: Install kubectl
  block:
    - name: Install kubectl on Debian-based systems
      package:
        name: kubectl
        state: present
      when: ansible_os_family == 'Debian'

    - name: Install kubectl on Fedora-based systems
      package:
        name: kubernetes-client
        state: present
      when: ansible_os_family == 'RedHat'

    - name: Install kubectl on Arch-based systems
      package:
        name: kubectl
        state: present
      when: ansible_os_family == 'Archlinux'

- name: Install k9s
  block:
    - name: Install k9s on Debian-based systems
      apt:
        name: k9s
        state: present
      when: ansible_os_family == 'Debian'

    - name: Install k9s on Fedora-based systems
      dnf:
        name: k9s
        state: present
      when: ansible_os_family == 'RedHat'

    - name: Install k9s on Arch-based systems
      pacman:
        name: k9s
        state: present
      when: ansible_os_family == 'Archlinux'

- name: Install k3s
  block:
    - name: Install k3s
      shell: curl -sfL https://get.k3s.io | sh -

- name: Install Helm
  block:
    - name: Install Helm on Debian-based systems
      shell: |
        curl https://baltocdn.com/helm/signing.asc | sudo apt-key add -
        sudo apt-get install apt-transport-https --yes
        echo "deb https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
        sudo apt-get update
        sudo apt-get install helm
      when: ansible_os_family == 'Debian'

    - name: Install Helm on Fedora-based systems
      shell: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      when: ansible_os_family == 'RedHat'

    - name: Install Helm on Arch-based systems
      pacman:
        name: helm
        state: present
      when: ansible_os_family == 'Archlinux'
