---
- name: Set Up distribution-specific Configurations 
  ansible.builtin.include_tasks: "{{ ansible_distribution | lower }}.yml"

- name: Ensure .ssh directory exists
  ansible.builtin.file:
    path: "/home/{{ username }}/.ssh"
    state: directory
    mode: '0700'
- name: Configure Git user name
  community.general.git_config:
    name: user.name
    scope: global
    value: "{{ github_user }}"

- name: Configure Git user email
  community.general.git_config:
    name: user.email
    scope: global
    value: "{{ github_email }}"
- name: Generate SSH key
  community.crypto.openssh_keypair:
    path: "/home/{{ username }}/.ssh/id_rsa"
    type: rsa
    size: 4096
    mode: '0600'
    comment: "{{ github_email }}"
    regenerate: full_idempotence
  register: ssh_key

- name: Display SSH public key
  ansible.builtin.debug:
    msg: "{{ ssh_key.public_key }}"

- name: Add SSH key to GitHub account
  shell: gh ssh-key add "/home/{{ username }}/.ssh/id_rsa.pub" --title "{{ansible_hostname}}-{{ username }}"
