---
- name: Set Up distribution-specific Configurations 
  ansible.builtin.include_tasks: "{{ ansible_distribution | lower }}.yml"

- name: Configure Git user name
  community.general.git_config:
    name: user.name
    scope: global
    value: "{{ github_user }}"

- name: Configure Git user email
  community.general.git_config:
    name: user.email
    scope: global
    value: "{{ github_email }}"

- name: Ensure .ssh directory exists
  ansible.builtin.file:
    path: "/home/{{ username }}/.ssh"
    state: directory
    mode: '0700'

- name: Generate SSH key
  ansible.builtin.openssh_keypair:
    path: "/home/{{ username }}/.ssh/id_rsa"
    type: rsa
    size: 4096
    mode: '0600'
    comment: "{{ github_email }}"
  register: ssh_key

- name: enable ssh-agent
  shell: eval $(ssh-agent)

- name: Add SSH private key to the agent
  ansible.builtin.command: ssh-add "/home/{{ username }}/.ssh/id_rsa"

- name: Display SSH public key
  ansible.builtin.debug:
    msg: "{{ ssh_key.public_key }}"

- name: Add SSH key to GitHub account
  shell: gh ssh-key add "/home/{{ username }}/.ssh/id_rsa.pub" --title "ansible-key-{{ ansible_date_time.iso8601 }}"
