---
- name: Determine the OS
  shell: cat /etc/os-release | grep "^ID="
  register: os_id
  changed_when: false

- name: Set package list based on OS
  set_fact:
    packages: "{{ fedora_packages }}" 
  when: os_id.stdout.find('fedora') != -1

- name: Set package list based on OS
  set_fact:
    packages: "{{ debian_packages }}"
  when: os_id.stdout.find('debian') != -1

- name: Set package list based on OS
  set_fact:
    packages: "{{ endeavoros_packages }}"
  when: os_id.stdout.find('endeavouros') != -1

- name: Update all packages and firmware on Debian
  apt: 
    update_cache: yes
    upgrade: dist
  when: os_id.stdout.find('debian') != -1

- name: Update all packages and firmware on Fedora
  dnf:
    name: '*'
    state: latest
  when: os_id.stdout.find('fedora') != -1

- name: Update all packages and firmware on EndeavourOS
  pacman:
    update_cache: yes
    upgrade: yes
  when: os_id.stdout.find('endeavouros') != -1

- name: Install necessary packages
  package:
    name: "{{ packages }}"
    state: present

