---
  - name: Ensure genfstab is installed
    ansible.builtin.package:
      name: arch-install-scripts
      state: present
    become: true

  - name: Backup existing fstab
    ansible.builtin.copy:
      src: /etc/fstab
      dest: /etc/fstab.bak
      backup: yes
    become: true

  - name: Generate a new fstab with genfstab
    ansible.builtin.command: genfstab -U /
    register: genfstab_output
    become: true

  - name: Append new fstab entries to /etc/fstab
    ansible.builtin.lineinfile:
      path: /etc/fstab
      line: "{{ item }}"
      state: present
      insertafter: EOF
    loop: "{{ genfstab_output.stdout_lines }}"
    become: true

  - name: Test the new fstab configuration by mounting all entries
    ansible.builtin.command: mount -a
    ignore_errors: true
    become: true
