---
- name: Detect all storage devices
  command: lsblk -o NAME,TYPE,FSTYPE,SIZE,MOUNTPOINT -J
  register: lsblk_output

- name: Parse storage devices
  set_fact:
    devices: "{{ lsblk_output.stdout | from_json | json_query('blockdevices[?type==`disk` || type==`part` || type==`lvm` || type==`crypt`].{name: name, fstype: fstype, mountpoint: mountpoint, size: size}') }}"

- name: Generate fstab entries
  set_fact:
    fstab_entries: >-
      {{ devices | selectattr('mountpoint', 'defined') | map('regex_replace', '^', 'UUID=') | join('\n') }}

- name: Ensure backup of fstab
  copy:
    src: /etc/fstab
    dest: /etc/fstab.bak
    backup: yes
  become: true

- name: Add storage devices to fstab
  blockinfile:
    path: /etc/fstab
    marker: "# {mark} ANSIBLE MANAGED BLOCK - STORAGE DEVICES"
    block: |
      {{ fstab_entries }}
  become: true

- name: Mount all filesystems
  command: mount -a
  become: true
