- name: Install NVIDIA drivers on EndeavourOS
  pacman:
    name: "{{ item }}"
    state: present
  loop:
    - nvidia
    - nvidia-utils
    - lib32-nvidia-utils
    - vulkan-icd-loader
    - lib32-vulkan-icd-loader
    - vulkan-tools
    - nvidia-libgl
    - lib32-nvidia-libgl
  when: gpu_vendor == 'nvidia'
  become: true

  - name: Install AMD drivers on EndeavourOS
  pacman:
    name: "{{ item }}"
    state: present
  loop:
    - xf86-video-amdgpu
    - vulkan-radeon
  when: gpu_vendor == 'amd'
  become: true

- name: Disable Nouveau on EndeavorOS
  ansible.builtin.lineinfile:
    path: /etc/kernel/cmdline
    line: "nouveau.modeset=0"
  when: gpu_vendor == 'nvidia'
  notify: Reinstall kernels