---
- name: Detect GPU hardware
  ansible.builtin.shell: lspci | grep -E "VGA|3D"
  register: gpu_info
  changed_when: false

- name: Set GPU vendor fact
  ansible.builtin.set_fact:
    gpu_vendor: "{{ 'nvidia' if 'NVIDIA' in gpu_info.stdout else 'amd' if 'AMD' in gpu_info.stdout else 'unknown' }}"

- name: debug
  debug:
    msg: "{{ kepler }}"

- name: Set GPU Hardware Series Fact
  ansible.builtin.set_fact:
    kepler: "{{ kepler }}"

- name: Set Up distribution-specific GPU Configurations 
  ansible.builtin.include_tasks: "{{ ansible_distribution | lower }}.yml"

# - name: Blacklist Nouveau driver
#   community.general.kernel_blacklist:
#     name: nouveau
#     state: present
#   notify: Update initramfs

# - name: Create modprobe config file
#   ansible.builtin.copy:
#     content: "options nouveau modeset=0"
#     dest: /etc/modprobe.d/nouveau-kms.conf

# - name: Ensure GRUB is updated
#   ansible.builtin.command: "{{ grub_update_cmd }}"
#   when: grub_update_cmd is defined
#   changed_when: true

# - name: Test Vulkan installation
#   shell: vulkaninfo
#   register: vulkan_test
#   ignore_errors: yes
#   become: true

# - name: Print Vulkan test results
#   debug:
#     msg: "{{ vulkan_test.stdout }}"
