---
- name: Detect GPU type
  shell: lshw -C display | grep vendor | awk '{print $2}'
  register: gpu_vendor
  become: true

- name: Install NVIDIA drivers on Debian
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - nvidia-driver
    - nvidia-settings
    - vulkan-utils
    - nvidia-cuda-toolkit
  when: gpu_vendor.stdout.find('NVIDIA') != -1 and os_id.stdout.find('debian') != -1
  become: true

- name: Install NVIDIA drivers on Fedora
  dnf:
    name: "{{ item }}"
    state: present
  loop:
    - akmod-nvidia
    - xorg-x11-drv-nvidia
    - xorg-x11-drv-nvidia-libs
    - xorg-x11-drv-nvidia-cuda
    - vulkan
    - vulkan-tools
    - vulkan-loader
  when: gpu_vendor.stdout.find('NVIDIA') != -1 and os_id.stdout.find('fedora') != -1
  become: true

- name: Install NVIDIA drivers on EndeavourOS
  pacman:
    name: "{{ item }}"
    state: present
  loop:
    - nvidia
    - nvidia-utils
    - lib32-nvidia-utils
    - vulkan-icd-loader
    - lib32-vulkan-icd-loader
    - vulkan-tools
    - nvidia-libgl
    - lib32-nvidia-libgl
  when: gpu_vendor.stdout.find('NVIDIA') != -1 and os_id.stdout.find('endeavouros') != -1
  become: true

- name: Install AMD drivers on Debian
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - mesa-vulkan-drivers
    - vulkan-utils
  when: gpu_vendor.stdout.find('AMD') != -1 and os_id.stdout.find('debian') != -1
  become: true

- name: Install AMD drivers on Fedora
  dnf:
    name: "{{ item }}"
    state: present
  loop:
    - xorg-x11-drv-amdgpu
    - vulkan
  when: gpu_vendor.stdout.find('AMD') != -1 and os_id.stdout.find('fedora') != -1
  become: true

- name: Install AMD drivers on EndeavourOS
  pacman:
    name: "{{ item }}"
    state: present
  loop:
    - xf86-video-amdgpu
    - vulkan-radeon
  when: gpu_vendor.stdout.find('AMD') != -1 and os_id.stdout.find('endeavouros') != -1
  become: true

- name: Test Vulkan installation
  shell: vulkaninfo
  register: vulkan_test
  ignore_errors: yes
  become: true

- name: Print Vulkan test results
  debug:
    msg: "{{ vulkan_test.stdout }}"
